
const CHANNELS = Object.freeze({
  FROM_SERVER: "FROM_SERVER",
  FROM_BACKGROUND: "FROM_BACKGROUND",
  FROM_CONTENT_SCRIPT: "FROM_CONTENT_SCRIPT",
  FROM_POPUP: "FROM_POPUP",
});

const SESSION_EVENTS = Object.freeze({
  REGISTER_HOST: "REGISTER_HOST",
  JOIN_PAIR: "JOIN_PAIR", // Legacy

  HOST_REGISTERED: "HOST_REGISTERED",
  PAIR_JOINED: "PAIR_JOINED", // Legacy
  PAIR_INVALID: "PAIR_INVALID",
  REQUEST_PAIR_CODE: "REQUEST_PAIR_CODE",
  PAIR_CODE: "PAIR_CODE",
  HOST_DISCONNECTED: "HOST_DISCONNECTED",

  REMOTE_JOIN_REQUEST: "REMOTE_JOIN_REQUEST",
  REMOTE_APPROVED: "REMOTE_APPROVED",
  REMOTE_JOINED: "REMOTE_JOINED",

  GET_SESSION_IDENTITY: "GET_SESSION_IDENTITY",
});


const CONTROL_EVENTS = Object.freeze({
  CONTROL_EVENT: "CONTROL_EVENT",
  STATE_UPDATE: "STATE_UPDATE",
});

const CONTROL_ACTIONS = Object.freeze({
  TOGGLE_PLAYBACK: "TOGGLE_PLAYBACK",
});

const MEDIA_EVENTS = Object.freeze({
  MEDIA_TABS_LIST: "MEDIA_TABS_LIST",
  SELECT_ACTIVE_TAB: "SELECT_ACTIVE_TAB",
});

const TAB_ACTIVITY = Object.freeze({
  TAB_CREATED: "TAB_CREATED",
  TAB_CLOSED: "TAB_CLOSED",
  TAB_ACTIVE: "TAB_ACTIVE",
  TAB_LOAD_COMPLETE: "TAB_LOAD_COMPLETE",
});

const ROLES = Object.freeze({
  HOST: "HOST",
  REMOTE: "REMOTE",
});

const MEDIA_URL_PATTERNS = Object.freeze([
  "youtube.com",
  "netflix.com",
  "primevideo.com",
  "hotstar.com",
  "vimeo.com",
]);

const TRIGGERS = Object.freeze({
  ...SESSION_EVENTS,
  ...CONTROL_EVENTS,
  ...MEDIA_EVENTS,
  ...CHANNELS,
  ROLE: ROLES,
});

export {
  CHANNELS,
  SESSION_EVENTS,
  CONTROL_EVENTS,
  CONTROL_ACTIONS,
  MEDIA_EVENTS,
  TAB_ACTIVITY,
  ROLES,
  MEDIA_URL_PATTERNS,
  TRIGGERS,
};
