const CONNECTION = Object.freeze({
    REGISTER_HOST: 'REGISTER_HOST',
    JOIN_PAIR: 'JOIN_PAIR',
    HOST_REGISTERED: 'HOST_REGISTERED',
    PAIR_JOINED: 'PAIR_JOINED',
    REMOTE_JOINED: 'REMOTE_JOINED',
    PAIR_INVALID: 'PAIR_INVALID',
    CONTROL_EVENT: 'CONTROL_EVENT',
    STATE_UPDATE: 'STATE_UPDATE',
    REMOTE_APPROVED: 'REMOTE_APPROVED',
    REMOTE_JOIN_REQUEST: 'REMOTE_JOIN_REQUEST',
    ROLE: {
        HOST: 'HOST',
        REMOTE: 'REMOTE',
    }
});

export default CONNECTION;