export const CONNECTION_STATUS = Object.freeze({
  DISCONNECTED: "Disconnected",
  CONNECTING: "Connecting",
  CONNECTED:"Connected",
  VERIFYING: "Verifying",
  SCANNING: "Scanning",
  PAIRED: "Paired",
  WAITING: "Waiting",
});

export const PLAYBACK_STATE = Object.freeze({
  PLAY: "Play",
  PAUSE: "Pause",
});

export const MSG = Object.freeze({
  EXCHANGE_PAIR_CODE: "EXCHANGE_PAIR_CODE",
  PAIR_SUCCESS: "PAIR_SUCCESS",
  PAIR_FAILED: "PAIR_FAILED",
  VALIDATE_SESSION: "VALIDATE_SESSION",
  SESSION_VALID: "SESSION_VALID",
  SESSION_INVALID: "SESSION_INVALID",
  HOST_DISCONNECTED: "HOST_DISCONNECTED",
  MEDIA_TABS_LIST: "MEDIA_TABS_LIST",
  STATE_UPDATE: "STATE_UPDATE",
  SELECT_ACTIVE_TAB: "SELECT_ACTIVE_TAB",
  CONTROL_EVENT: "CONTROL_EVENT",
  TOGGLE_PLAYBACK: "TOGGLE_PLAYBACK",
});
