const PROTOCOL = Object.freeze({
  SESSION: {
    REGISTER_HOST: "REGISTER_HOST",
    JOIN_PAIR: "JOIN_PAIR",
    HOST_REGISTERED: "HOST_REGISTERED",
    PAIR_JOINED: "PAIR_JOINED",
    PAIR_INVALID: "PAIR_INVALID",
    REMOTE_JOINED: "REMOTE_JOINED",
  },

  CONTROL: {
    EVENT: "CONTROL_EVENT",
    STATE_UPDATE: "STATE_UPDATE",
  },

  MEDIA: {
    TABS_LIST: "MEDIA_TABS_LIST",
    SELECT_ACTIVE_TAB: "SELECT_ACTIVE_TAB",
  },

  ROLE: {
    HOST: "HOST",
    REMOTE: "REMOTE",
  },
});

module.exports = PROTOCOL;
