const PROTOCOL = Object.freeze({
  SESSION: {
    REGISTER_HOST: "REGISTER_HOST",
    HOST_REGISTERED: "HOST_REGISTERED",
    REQUEST_PAIR_CODE: "REQUEST_PAIR_CODE",
    PAIR_CODE: "PAIR_CODE",
    EXCHANGE_PAIR_CODE: "EXCHANGE_PAIR_CODE",
    PAIR_SUCCESS: "PAIR_SUCCESS",
    PAIR_FAILED: "PAIR_FAILED",
    VALIDATE_SESSION: "VALIDATE_SESSION",
    SESSION_VALID: "SESSION_VALID",
    SESSION_INVALID: "SESSION_INVALID",
    REMOTE_JOINED: "REMOTE_JOINED",
    HOST_DISCONNECTED: "HOST_DISCONNECTED",
  },

  CONTROL: {
    EVENT: "CONTROL_EVENT",
    STATE_UPDATE: "STATE_UPDATE",
  },

  MEDIA: {
    TABS_LIST: "MEDIA_TABS_LIST",
    SELECT_ACTIVE_TAB: "SELECT_ACTIVE_TAB",
  },

  ROLE: {
    HOST: "HOST",
    REMOTE: "REMOTE",
  },
});

module.exports = PROTOCOL;
